-- return {
--   dir = "~/Projects/plugins/youversion-linker.nvim",
--   name = "youversion-linker",
--   config = function()
--     require("test-youversion-linker").setup()
--   end
-- }
-- return {
--   dir = "~/Projects/plugins/youversion-linker.nvim",
--   name = "youversion-linker",
--   config = function()
--     local module = require("blink-youversion-linker")
--     print("Module type:", type(module))
--     print("Module setup type:", type(module.setup))
--     if type(module.setup) == "function" then
--       module.setup()
--     else
--       print("Setup is not a function, it's:", module.setup)
--     end
--   end
-- }
return {
  {
    dir = "~/Projects/plugins/youversion-linker.nvim",
    name = "youversion-linker",
    event = "InsertEnter", -- Load when entering insert mode
    -- dependencies = { "saghen/blink.cmp" },

    -- opts = {
    --   bible_versions = {
    --     NIV = { enabled = true, priority = 1 },
    --     ESV = { enabled = true, priority = 2 },
    --     KJV = { enabled = true, priority = 3 },
    --   },
    -- },
    config = function()
      require("nui.bible-completion.init").setup({
        -- debounce_ms = 250,
        -- popup = {
        --   size = { width = 60, height = 12 },
        --   border = { style = "double" },
        -- },
        -- keymaps = {
        --   select = { "<CR>", "<Tab>" },
        --   close = { "<Esc>", "q", "<C-c>" },
        -- },
        -- bible_versions = {
        --   ESV = { enabled = true },
        --   MSG = { enabled = true },
        -- }
      })
    end
  },
  -- Configure blink.cmp to use the bible source
  -- {
  --   "saghen/blink.cmp",
  --   optional = true,
  --   config = function()
  --     require('blink.cmp').setup({
  --       sources = {
  --         providers = {
  --           bible = {
  --             name = "bible",
  --             module = "path.to.your.bible.source", -- This should be the module path to your bible source file
  --             enabled = true,
  --           },
  --           -- Your other sources...
  --           lsp = { 
  --             name = "LSP", 
  --             module = "blink.cmp.sources.lsp",
  --             enabled = true 
  --           },
  --           path = { 
  --             name = "Path", 
  --             module = "blink.cmp.sources.path", 
  --             enabled = true 
  --           },
  --           snippets = { 
  --             name = "Snippets", 
  --             module = "blink.cmp.sources.snippets", 
  --             enabled = true 
  --           },
  --           buffer = { 
  --             name = "Buffer", 
  --             module = "blink.cmp.sources.buffer", 
  --             enabled = true 
  --           },
  --         },
  --       },
  --       keymap = {
  --         preset = 'default',
  --       },
  --     })
  --   end
  -- },
}
  -- config = function()
  --   -- User configuration example (init.lua or plugin config)
  --   require("bible-linker").setup({
  --     -- Bible version to use by default
  --     bible_version = "NIV",  -- Can be changed with :BibleSetVersion ESV
  --
  --     -- Trigger characters (can be customized)
  --     triggers = {
  --       link = "@",      -- Creates markdown link to YouVersion
  --       quote = ">",     -- Inserts verse text as blockquote
  --       footnote = "^"   -- Creates footnote with verse text
  --     },
  --
  --     -- Enable auto-completion
  --     auto_complete = true,
  --
  --     -- Keymaps
  --     keymaps = {
  --       lookup = "<leader>bl",        -- Manual Bible lookup
  --       process_line = "<leader>bp"   -- Process current line/selection
  --     },
  --
  --     -- Auto-process lines when leaving insert mode (optional)
  --     auto_process = false  -- Set to true for automatic processing
  --   })
  --
    -- Usage Examples:
    -- 1. Link to verse: Type "@John 3:16" then press <leader>bp
    --    Result: [John 3:16](https://www.bible.com/bible/111/JHN.3.16.NIV)
    --
    -- 2. Quote verse: Type ">John 3:16" then press <leader>bp  
    --    Result: > For God so loved the world that he gave his one and only Son...
    --            > 
    --            > *John 3:16 (NIV)*
    --
    -- 3. Footnote: Type "^John 3:16" then press <leader>bp
    --    Result: [^John316] (in text) and footnote at bottom:
    --            [^John316]: For God so loved the world... - John 3:16 (NIV)
    --
    -- 4. With specific version: "@John 3:16 ESV" or ">Romans 8:28 NASB"
    --
    -- Commands:
    -- :BibleLookup John 3:16        - Manual lookup and insert
    -- :BibleProcessLine             - Process current line
    -- :BibleProcessBuffer           - Process entire buffer  
    -- :BibleSetVersion ESV          - Change default version
    -- :BibleSetVersion              - Show current version
--   end
-- }
